# Generated by Django 6.0.7 on 2026-07-19 02:01

import dashboards.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_weight_kg', models.FloatField(blank=True, null=True)),
                ('birth_height_cm', models.FloatField(blank=True, null=True)),
                ('is_alive', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BabyDevelopmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('age_in_weeks', models.IntegerField(help_text="Baby's age in weeks at recording")),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('head_circumference_cm', models.FloatField(blank=True, null=True)),
                ('feeding_type', models.CharField(blank=True, choices=[('breastfeeding', 'Breastfeeding'), ('formula', 'Formula'), ('mixed', 'Mixed'), ('other', 'Other')], max_length=30)),
                ('milestones_achieved', models.TextField(blank=True, help_text='e.g., smiles, holds head, coos, etc.')),
                ('concerns', models.TextField(blank=True, help_text='Any developmental concerns')),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_records', to='dashboards.babyprofile')),
            ],
            options={
                'verbose_name': 'Baby Development Record',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Clinics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clinics', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to='accounts.hospitalprofile')),
                ('staff', models.ManyToManyField(blank=True, related_name='clinics', to='accounts.hospitalstaffprofile')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='KickCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('session_start', models.DateTimeField(auto_now_add=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kicks', to='accounts.motherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('result_value', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('normal_range', models.CharField(blank=True, max_length=50, null=True)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('taken_date', models.DateField()),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=dashboards.models.lab_attachment_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dashboards.labtest')),
            ],
        ),
        migrations.CreateModel(
            name='Link_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linker_type', models.CharField(max_length=20)),
                ('link_type', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('member_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_link_request', to=settings.AUTH_USER_MODEL)),
                ('linker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_linker_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MotherWeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to='accounts.motherprofile')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancy_number', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('last_menstrual_period', models.DateField(blank=True, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('pre_pregnancy_weight', models.FloatField(blank=True, null=True)),
                ('is_high_risk', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('delivered', 'Delivered'), ('completed', 'Completed')], default='ongoing', max_length=20)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancies', to='accounts.motherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MoHVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('gestational_age', models.IntegerField(help_text='Weeks')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20)),
                ('sfh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Symphysio-Fundal Height')),
                ('fetal_heart_rate', models.IntegerField(blank=True, null=True)),
                ('urine_sugar', models.CharField(blank=True, max_length=20)),
                ('urine_albumin', models.CharField(blank=True, max_length=20)),
                ('complaints', models.TextField(blank=True)),
                ('advice', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.doctorprofile')),
                ('midwife', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.midwifeprofile')),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='dashboards.pregnancy')),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='MidwifeVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('trimester', models.IntegerField()),
                ('visit_type', models.CharField(choices=[('routine', 'Routine Checkup'), ('growth', 'Growth Check'), ('risk', 'Risk Review'), ('lab', 'Lab Follow-up')], default='routine', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midwife_visits', to='dashboards.pregnancy')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.pregnancy')),
            ],
        ),
        migrations.AddField(
            model_name='labtest',
            name='pregnancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='dashboards.pregnancy'),
        ),
        migrations.CreateModel(
            name='FetalHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('movement_level', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=20)),
                ('growth_status', models.CharField(blank=True, max_length=50, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetal_records', to='dashboards.pregnancy')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('bleeding', 'Bleeding'), ('high_bp', 'High Blood Pressure'), ('no_movement', 'No Fetal Movement'), ('pain', 'Severe Pain'), ('other', 'Other')], max_length=50)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('triggered_by_ai', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='dashboards.pregnancy')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('week_due', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('auto_generated', models.BooleanField(default=True)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='dashboards.pregnancy')),
            ],
        ),
        migrations.AddField(
            model_name='babyprofile',
            name='pregnancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='babies', to='dashboards.pregnancy'),
        ),
        migrations.CreateModel(
            name='PregnancyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('bp_systolic', models.IntegerField(blank=True, null=True)),
                ('bp_diastolic', models.IntegerField(blank=True, null=True)),
                ('baby_heart_rate', models.IntegerField(blank=True, null=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='dashboards.pregnancy')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('factors', models.JSONField(default=dict)),
                ('prediction_model_version', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='dashboards.pregnancy')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('midwife_visit', 'Midwife Visit'), ('doctor_appointment', 'Doctor Appointment'), ('hospital_clinic', 'Hospital Clinic'), ('ultrasound', 'Ultrasound Scan'), ('lab_test', 'Lab Test Appointment'), ('milestone', 'Important Milestone'), ('other', 'Other')], default='midwife_visit', max_length=50)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('what_to_bring', models.TextField(blank=True, help_text='Items mother should bring')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='dashboards.clinics')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_events', to='dashboards.pregnancy')),
            ],
            options={
                'ordering': ['scheduled_date', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='TrimesterPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_trimester', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pregnancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trimester_plan', to='dashboards.pregnancy')),
            ],
        ),
        migrations.CreateModel(
            name='TrimesterTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimester', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')])),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('week_range', models.CharField(max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trimester_tasks', to='dashboards.pregnancy')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('dose_number', models.IntegerField()),
                ('date_given', models.DateField()),
                ('given_by', models.CharField(blank=True, max_length=150)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='dashboards.pregnancy')),
            ],
        ),
        migrations.CreateModel(
            name='VisitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('notes', models.TextField()),
                ('findings', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_notes', to='dashboards.pregnancy')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('scheduled_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboards.scheduleevent')),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='WaterIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_ml', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_logs', to='accounts.motherprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField(auto_now_add=True)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to='accounts.motherprofile')),
            ],
        ),
    ]
