# Generated by Django 5.2.11 on 2026-06-16 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linker_type', models.CharField(max_length=20)),
                ('link_type', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('member_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_link_request', to=settings.AUTH_USER_MODEL)),
                ('linker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_linker_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
