# Generated by Django 5.2.11 on 2026-05-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_motherweightrecord_notification_pregnancy_medication_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregnancy',
            old_name='edd',
            new_name='expected_delivery_date',
        ),
        migrations.RenameField(
            model_name='pregnancy',
            old_name='lmp_date',
            new_name='last_menstrual_period',
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='pre_pregnancy_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
