# Generated by Django 5.2.11 on 2026-05-16 10:27

import dashboards.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_fetalhealth_recorded_by_labtest_recorded_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=dashboards.models.lab_attachment_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dashboards.labtest')),
            ],
        ),
    ]
