# Generated by Django 5.2.11 on 2026-05-16 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_labattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('week_due', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('auto_generated', models.BooleanField(default=True)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='dashboards.pregnancy')),
            ],
        ),
        migrations.CreateModel(
            name='MidwifeVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('trimester', models.IntegerField()),
                ('visit_type', models.CharField(choices=[('routine', 'Routine Checkup'), ('growth', 'Growth Check'), ('risk', 'Risk Review'), ('lab', 'Lab Follow-up')], default='routine', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midwife_visits', to='dashboards.pregnancy')),
            ],
        ),
        migrations.CreateModel(
            name='TrimesterPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_trimester', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pregnancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trimester_plan', to='dashboards.pregnancy')),
            ],
        ),
    ]
