# Generated by Django 5.2.11 on 2026-05-16 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_clinicalmilestone_midwifevisit_trimesterplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('midwife_visit', 'Midwife Visit'), ('doctor_appointment', 'Doctor Appointment'), ('hospital_clinic', 'Hospital Clinic'), ('ultrasound', 'Ultrasound Scan'), ('lab_test', 'Lab Test Appointment'), ('milestone', 'Important Milestone'), ('other', 'Other')], default='midwife_visit', max_length=50)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('what_to_bring', models.TextField(blank=True, help_text='Items mother should bring')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_events', to='dashboards.pregnancy')),
            ],
            options={
                'ordering': ['scheduled_date', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='TrimesterTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimester', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')])),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('week_range', models.CharField(max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trimester_tasks', to='dashboards.pregnancy')),
            ],
        ),
    ]
