# Generated by Django 5.2.11 on 2026-05-17 14:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0007_scheduleevent_trimestertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregnancy',
            name='actual_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('delivered', 'Delivered'), ('completed', 'Completed')], default='ongoing', max_length=20),
        ),
        migrations.CreateModel(
            name='BabyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_weight_kg', models.FloatField(blank=True, null=True)),
                ('birth_height_cm', models.FloatField(blank=True, null=True)),
                ('is_alive', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('pregnancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baby', to='dashboards.pregnancy')),
            ],
        ),
    ]
