# Generated by Django 5.2.11 on 2026-05-23 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_doctorprofile_designation_midwifeprofile_license_no_and_more'),
        ('dashboards', '0009_visitnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoHVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('gestational_age', models.IntegerField(help_text='Weeks')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20)),
                ('sfh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Symphysio-Fundal Height')),
                ('fetal_heart_rate', models.IntegerField(blank=True, null=True)),
                ('urine_sugar', models.CharField(blank=True, max_length=20)),
                ('urine_albumin', models.CharField(blank=True, max_length=20)),
                ('complaints', models.TextField(blank=True)),
                ('advice', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.doctorprofile')),
                ('midwife', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.midwifeprofile')),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='dashboards.pregnancy')),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('dose_number', models.IntegerField()),
                ('date_given', models.DateField()),
                ('given_by', models.CharField(blank=True, max_length=150)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='dashboards.pregnancy')),
            ],
        ),
    ]
