# Generated by Django 5.2.11 on 2026-05-24 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0010_mohvisit_vaccination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='babyprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='BabyDevelopmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('age_in_weeks', models.IntegerField(help_text="Baby's age in weeks at recording")),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('head_circumference_cm', models.FloatField(blank=True, null=True)),
                ('feeding_type', models.CharField(blank=True, choices=[('breastfeeding', 'Breastfeeding'), ('formula', 'Formula'), ('mixed', 'Mixed'), ('other', 'Other')], max_length=30)),
                ('milestones_achieved', models.TextField(blank=True, help_text='e.g., smiles, holds head, coos, etc.')),
                ('concerns', models.TextField(blank=True, help_text='Any developmental concerns')),
                ('notes', models.TextField(blank=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_records', to='dashboards.babyprofile')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Baby Development Record',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
