# Generated by Django 5.2.11 on 2026-05-24 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0012_alter_babyprofile_pregnancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babyprofile',
            name='pregnancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='babies', to='dashboards.pregnancy'),
        ),
    ]
