# Generated by Django 5.2.11 on 2026-05-10 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_midwifeprofile_is_verified'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalgroup',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='accounts.hospitalprofile'),
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
