# Generated by Django 5.2.11 on 2026-06-18 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('dashboards', '0002_link_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='pregnancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preg_fam', to='dashboards.pregnancy'),
        ),
    ]
