# Generated by Django 5.2.11 on 2026-05-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='midwifeprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
