# Generated by Django 6.0.7 on 2026-07-19 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='pregnancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preg_fam', to='dashboards.pregnancy'),
        ),
        migrations.AddField(
            model_name='familyinvitation',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.family'),
        ),
        migrations.AddField(
            model_name='familyinvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familyinvitation',
            name='invited_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fatherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_father', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='family',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_familiy', to='accounts.fatherprofile'),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_hospital', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='family',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_familiy', to='accounts.hospitalprofile'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.hospitalprofile'),
        ),
        migrations.AddField(
            model_name='hospitalstaffprofile',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='accounts.hospitalprofile'),
        ),
        migrations.AddField(
            model_name='hospitalstaffprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_hospital_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='midwifeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_midwife', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='family',
            name='midwife',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='midwife_familiy', to='accounts.midwifeprofile'),
        ),
        migrations.AddField(
            model_name='motherdetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='motherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_mother', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='motherdetails',
            name='mother',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mother_details', to='accounts.motherprofile'),
        ),
        migrations.AddField(
            model_name='fatherprofile',
            name='linked_mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father', to='accounts.motherprofile'),
        ),
        migrations.AddField(
            model_name='family',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mom_familiy', to='accounts.motherprofile'),
        ),
        migrations.AddField(
            model_name='verifydoc',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments_verify', to=settings.AUTH_USER_MODEL),
        ),
    ]
