# Generated by Django 5.2.11 on 2026-05-10 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_midwifeprofile_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_hospital', to=settings.AUTH_USER_MODEL),
        ),
    ]
