# Generated by Django 5.2.11 on 2026-05-10 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_hospitalprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fatherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_father', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='midwifeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_midwife', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='motherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_mother', to=settings.AUTH_USER_MODEL),
        ),
    ]
