# Generated by Django 5.2.11 on 2026-05-16 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_motherdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motherdetails',
            name='expected_delivery_date',
        ),
        migrations.RemoveField(
            model_name='motherdetails',
            name='last_menstrual_period',
        ),
        migrations.RemoveField(
            model_name='motherdetails',
            name='pre_pregnancy_weight',
        ),
    ]
