# Generated by Django 5.2.11 on 2026-05-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_motherdetails_expected_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
