# Generated by Django 5.2.11 on 2026-05-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_doctorprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='designation',
            field=models.CharField(blank=True, help_text='e.g., Consultant VOG, Medical Officer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='midwifeprofile',
            name='license_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='midwifeprofile',
            name='moh_area',
            field=models.CharField(blank=True, help_text='MOH Area', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='midwifeprofile',
            name='phm_area',
            field=models.CharField(blank=True, help_text='PHM Area', max_length=150, null=True),
        ),
    ]
