# Generated by Django 5.2.11 on 2026-05-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_doctorprofile_designation_midwifeprofile_license_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalprofile',
            name='address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='district',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
