# Generated by Django 5.2.11 on 2026-05-23 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_hospitalprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='VerifyDocs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments_verify', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
