# Generated by Django 5.2.11 on 2026-05-24 11:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_verifydoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='qr_token',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fatherprofile',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/fathers/'),
        ),
        migrations.AddField(
            model_name='fatherprofile',
            name='qr_token',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/hospitals/'),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='qr_token',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='midwifeprofile',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/midwives/'),
        ),
        migrations.AddField(
            model_name='midwifeprofile',
            name='qr_token',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='motherprofile',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/mothers/'),
        ),
        migrations.AddField(
            model_name='motherprofile',
            name='qr_token',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='FamilyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.family')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
