# Generated by Django 5.2.11 on 2026-05-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_doctorprofile_qr_code_doctorprofile_qr_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='qr_token',
        ),
        migrations.RemoveField(
            model_name='fatherprofile',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='fatherprofile',
            name='qr_token',
        ),
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='qr_token',
        ),
        migrations.RemoveField(
            model_name='midwifeprofile',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='midwifeprofile',
            name='qr_token',
        ),
        migrations.RemoveField(
            model_name='motherprofile',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='motherprofile',
            name='qr_token',
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='midwifeprofile',
            name='moh_area',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='midwifeprofile',
            name='phm_area',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
